//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BANK()
        {
            this.GUARANTEEs = new HashSet<GUARANTEE>();
            this.LOANS = new HashSet<LOAN>();
        }
    
        public int BankID { get; set; }
        public string BankCode { get; set; }
        public string BankName { get; set; }
        public byte MonthlyPaymentDate { get; set; }
        public byte GuaranteeLimit { get; set; }
        public byte CreditLimit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GUARANTEE> GUARANTEEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOAN> LOANS { get; set; }
    }
}
