//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GUARANTEE
    {
        public int GuaranteeID { get; set; }
        public int BankID { get; set; }
        public int GuaranteeTypeID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public byte GuaranteeAmount { get; set; }
        public decimal GuaranteeFee { get; set; }
        public string GuaranteeObject { get; set; }
        public string Status { get; set; }
    
        public virtual BANK BANK { get; set; }
        public virtual GUARANTEE_CATEGORIES GUARANTEE_CATEGORIES { get; set; }
    }
}
