//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CapBullEntities : DbContext
    {
        public CapBullEntities()
            : base("name=CapBullEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BANK> BANKS { get; set; }
        public virtual DbSet<GUARANTEE> GUARANTEEs { get; set; }
        public virtual DbSet<GUARANTEE_CATEGORIES> GUARANTEE_CATEGORIES { get; set; }
        public virtual DbSet<HOLIDAY> HOLIDAYS { get; set; }
        public virtual DbSet<INTEREST_RATES> INTEREST_RATES { get; set; }
        public virtual DbSet<LOAN_CATEGORIES> LOAN_CATEGORIES { get; set; }
        public virtual DbSet<LOAN> LOANS { get; set; }
        public virtual DbSet<PAY_PRINCIPLE> PAY_PRINCIPLE { get; set; }
        public virtual DbSet<PAYMENT> PAYMENTS { get; set; }
        public virtual DbSet<PERMISSION> PERMISSIONS { get; set; }
        public virtual DbSet<ROLE_PERMISSION> ROLE_PERMISSION { get; set; }
        public virtual DbSet<ROLE> ROLES { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TENANT> TENANTS { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<USERS_ROLES> USERS_ROLES { get; set; }
    }
}
