//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAY_PRINCIPLE
    {
        public int PayID { get; set; }
        public int LoanID { get; set; }
        public System.DateTime DatePaid { get; set; }
        public byte Amount { get; set; }
    
        public virtual LOAN LOAN { get; set; }
    }
}
