//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS_ROLES
    {
        public int RoleID { get; set; }
        public int UserID { get; set; }
    
        public virtual ROLE ROLE { get; set; }
        public virtual USER USER { get; set; }
    }
}
