//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapBullEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAN()
        {
            this.INTEREST_RATES = new HashSet<INTEREST_RATES>();
            this.PAY_PRINCIPLE = new HashSet<PAY_PRINCIPLE>();
        }
    
        public int LoanID { get; set; }
        public int BankID { get; set; }
        public int PaymentID { get; set; }
        public int LoanTypeID { get; set; }
        public int LoanAmount { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public byte LoanTerms { get; set; }
        public byte GracePeriod { get; set; }
    
        public virtual BANK BANK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INTEREST_RATES> INTEREST_RATES { get; set; }
        public virtual LOAN_CATEGORIES LOAN_CATEGORIES { get; set; }
        public virtual PAYMENT PAYMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAY_PRINCIPLE> PAY_PRINCIPLE { get; set; }
    }
}
