//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapBullEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLE_PERMISSION
    {
        public int PermissionID { get; set; }
        public int RoleID { get; set; }
    
        public virtual PERMISSION PERMISSION { get; set; }
        public virtual ROLE ROLE { get; set; }
    }
}
